/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.TenisDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Tenis;

/**
 *
 * @author tinho
 */
public class CadastrarTenis extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarTenis
     */
    public CadastrarTenis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNovoTenis = new javax.swing.JTextField();
        BttnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de TÍnis");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite o nome do novo TÍnis:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 24, -1, -1));

        jTextFieldNovoTenis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldNovoTenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNovoTenisActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNovoTenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 63, 172, 40));

        BttnSalvar.setText("Salvar");
        BttnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BttnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 121, 135, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/imgBackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -310, -1, -1));

        setSize(new java.awt.Dimension(288, 200));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNovoTenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNovoTenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNovoTenisActionPerformed

    private void BttnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnSalvarActionPerformed
        // TODO add your handling code here:
        String tenis = jTextFieldNovoTenis.getText();

        Tenis novoTenis = new Tenis(tenis);

        try {
            Connection conexao = new Conexao().getConnection();
            TenisDAO dao = new TenisDAO(conexao);

            String sql = "INSERT INTO tenis (tenis) VALUES ('" + tenis + "');";
            PreparedStatement statement = conexao.prepareStatement(sql);

            statement.execute();

            JOptionPane.showMessageDialog(null, "Tenis Salvo com sucesso!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Tenis n√£o foi salvo!");
            Logger.getLogger(CadastrarTenis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BttnSalvarActionPerformed

    public JTextField getjTextFieldNovoTenis() {
        return jTextFieldNovoTenis;
    }

    public void setjTextFieldNovoTenis(JTextField jTextFieldNovoTenis) {
        this.jTextFieldNovoTenis = jTextFieldNovoTenis;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarTenis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldNovoTenis;
    // End of variables declaration//GEN-END:variables
}
